# Generated by Django 4.1.1 on 2023-02-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work',
            field=models.CharField(choices=[('CP', 'Concrete Pavement'), ('WP', 'Wooden Patio Building/Repairment'), ('R', 'House Renovation'), ('HM', 'Home Moving'), ('SP', 'Snow Shovel'), ('O', 'Others')], default='CP', max_length=2),
        ),
    ]
