# Generated by Django 4.1.1 on 2023-02-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_job_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='name',
        ),
    ]
